version: '3.7'

services:

  pki-server:
    image: keyfactor/ejbca-ce:latest
    hostname: ${PKI_HOSTNAME}
    restart: unless-stopped
    networks:
      - front_network
      - back_network
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - pki-database
    environment:
      - DATABASE_JDBC_URL=jdbc:mariadb://pki-database:3306/ejbca?characterEncoding=UTF-8
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED="true"
    volumes:
      - ./ejbca_dir:/mnt/persistent

  pki-database:
    image: mariadb:10.9
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=foo123
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=ejbca
      - MYSQL_PASSWORD=ejbca
    volumes:
      - ./datadb_dir:/var/lib/mysql:rw
    networks:
      - back_network

networks:
  front_network:
    driver: bridge
  back_network:
    driver: bridge
    internal: true